version: '3'
services:
  tarifa-frontend:
    container_name: telzir-frontend
    build:
      context: .
      dockerfile: ./Docker/Front.Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - '5003:80'
    depends_on: 
        - tarifa-back

  tarifa-back:
    build:
      context: .
      dockerfile: ./Docker/Back.Dockerfile
    container_name: tarifa-back
    restart: unless-stopped